name: Notifications pre merge
permissions:
    contents: read
    actions: write
on:
  push:
    branches:
      - test

jobs:
  DispatchNotifications:
    runs-on: ubuntu-latest
    steps:
      - name: Get status changes and hipnames then dispatch jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run send-email.yml -f "filename=hip-25" -f "status=Draft"
      
      