name: Notifications pre merge
permissions:
    contents: read
    actions: write
on:
  push:
    branches:
      - test

jobs:
  DispatchNotifications:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      
      - name: Get status changes and hipnames then dispatch jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run send-email.yml -f "filename=hip-25" -f "status=Draft"