name: Send discord notification
on:
  workflow_dispatch:
    inputs:
      filename:
        type: string
        required: true
      status:
        type: string
        required: true

jobs:
  StatusChangeNotifications:
    runs-on: ubuntu-latest
    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        uses: step-security/action-discord@5e8cd69d2f322a15430c4d13a97659b58031d207 # v0.1.1
        with:
          args: "${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }} status https://hips.hedera.com/hip/${{ github.event.inputs.filename }}"
