name: Send status email
on:
  workflow_dispatch:
     inputs:
       filename:
          type: string
          required: true
       status:
          type: string
          required: true

permissions:
  contents: read

jobs:
  StatusChangeNotifications:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Send mail
        uses: step-security/action-send-mail@33e713f9796994f5437063c70594af025960a3b1 # v5.0.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: hips@hedera.com
          password: ${{secrets.GOOGLE_APP_PASS}}
          subject: ${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }}
          to: michael.garber@swirldslabs.com
          from: The HIPs repository
          body: This is an automated message, please do not reply. Check https://github.com/hashgraph/hedera-improvement-proposal for more info. Thank you.
          secure: true
          priority: medium