name: Send status email
on:
  workflow_dispatch:
     inputs:
       filename:
          type: string
          required: true
       status:
          type: string
          required: true

jobs:
  StatusChangeNotifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: hips@hedera.com
          password: ${{secrets.GOOGLE_APP_PASS}}
          subject: ${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }}
          to: ${{ github.event.inputs.status = 'Draft' && 'michael.garber@swirldslabs.com' || 'michaelgarber@gmail.com' }}
          from: The HIPs repository
          body: This is an automated message, please do not reply. Check https://github.com/hashgraph/hedera-improvement-proposal for more info. Thank you.
          secure: true
          priority: medium